# Generated by Django 3.2.6 on 2021-09-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('departament', models.CharField(max_length=50, verbose_name='Departamento')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ciudad')),
                ('direction', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dirección')),
                ('rh', models.CharField(choices=[('A+', 'A positivo'), ('A-', 'A negativo'), ('O+', 'O positivo'), ('O-', 'O negativo'), ('AB+', 'AB positivo'), ('AB-', 'AB negativo'), ('B+', 'B positivo'), ('B-', 'B negativo')], default='A+', max_length=3, verbose_name='Tipo de sangre')),
                ('email', models.CharField(max_length=50, verbose_name='Correo electronico')),
                ('gender', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('charge', models.CharField(choices=[('Secretari@', 'Secretari@'), ('Enfermer@', 'Enfermer@'), ('Doctor', 'Doctor'), ('Cirujano', 'Cirujano'), ('Recepcionista', 'Recepcionista'), ('Vigilante', 'Vigilante'), ('Aseo', 'Aseo')], default='Recepcionista', max_length=30, verbose_name='Cargo')),
                ('schedule', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleados',
            },
        ),
    ]
