# Generated by Django 3.2.6 on 2021-09-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='notas',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='state',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Alta', 'Alta'), ('Recuperación', 'Recuperación'), ('Sano', 'Sano'), ('requiere cirugia', 'requiere cirugia')], default='Sano', max_length=30),
        ),
    ]
