# Generated by Django 3.2.6 on 2021-09-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDatabase', '0002_auto_20210908_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='n_room',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Número de sala'),
        ),
    ]
