# Generated by Django 3.2.6 on 2021-09-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyDatabase', '0003_alter_rooms_n_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('ID_visitor', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='ID visitante')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Visitante')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos visitante')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad de residencia')),
                ('direction', models.CharField(max_length=60, verbose_name='Dirección de residencia')),
                ('email', models.CharField(max_length=80, unique=True, verbose_name='Correo Electronico')),
                ('relation', models.CharField(max_length=80, verbose_name='Relacion con el interno')),
                ('datevisit', models.DateField()),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyDatabase.patients')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'Visitantes',
            },
        ),
    ]
