# Generated by Django 3.2.6 on 2021-09-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('n_room', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Número de sala')),
                ('capacity', models.IntegerField(verbose_name='Capacidad de sala')),
                ('funtion', models.CharField(max_length=30, verbose_name='Función de la sala')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'Salas',
            },
        ),
    ]
