# Generated by Django 3.2.6 on 2021-09-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='names',
            new_name='name',
        ),
    ]
