# Generated by Django 3.2.6 on 2021-09-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de visitante')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('ID_visitor', models.CharField(max_length=50, unique=True, verbose_name='Número de documento')),
                ('cel_number', models.IntegerField(verbose_name='Número de celular')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Correo Electronico')),
                ('relation', models.CharField(max_length=30, verbose_name='Relación con el paciente')),
            ],
        ),
    ]
