# Generated by Django 3.2.6 on 2021-09-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitors',
            options={'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.AlterModelTable(
            name='visitors',
            table='Visitante',
        ),
    ]
